management:
    endpoints:
        web:
            exposure:
                include: info
    info:
        env:
            enabled: true
server:
    port: 8989

spring:
    application:
        name: API-GATEWAY-SERVICE
#    cloud:
#        gateway:
#            routes:
#                - id: COMPLIANCE-MASTER-SERVICE
#                  uri: lb://COMPLIANCE-MASTER-SERVICE
#                  predicates:
#                      - Path=/master/**
#
#                - id: COMPLIANCE-SERVICE
#                  uri: lb://COMPLIANCE-SERVICE
#                  predicates:
#                      - Path=/compliance/**
#
#                - id: COMPANY-SERVICE
#                  uri: lb://COMPANY-SERVICE
#                  predicates:
#                      - Path=/company/**,/login/**,/signup/**
#
#                - id: AUTHENTICATION-SERVICE
#                  uri: lb://AUTHENTICATION-SERVICE
#                  predicates:
#                    - Path=/auth/**
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
